#ifndef __DEFINITION_H__
#define __DEFINITION_H__

#define DISPLAY_TIME_SLASH_SCENE 2
#define TRANSITION_TIME 1.5

#define OBSTACLE_COLLISION_BITMASK 0x000001
#define BALL_COLLISION_BITMASK 0x000002
#define BOARD_COLLISION_BITMASK 0x000003
#define BLOCKS_COLLISION_BITMASK 0x000004

#endif // __DEFINITION_H__
